spring:
  application:
    name: campus-be
  datasource:
    url: ENC(iNWspP3aG2ofUHQ+N37My/J8thQ1P83FTPIFd6atCBUjAaaCJf1JGJO/Q81yMz1sukrNGVrYBJI=)
    username: ENC(xhIcr0c/P58Ncy/HjZ6bwA==)
    password: ENC(6Hn9BDx9NqK+CepfjQvO8w==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
oauth:
  kakao:
    client-id: ENC(G6gZHtP5QYz7+G6herJ1QCSbdVYgjtGnx8MhBSxLDFx26Yh0YQQ+uZ6RQ7wbvS17)
    client-secret: ENC(CG823WHRi6g4ybTc/VEOfd43c/RxVnIAE+AVpYWqrE/2xnGkvtjKkVSVVOXkXBXo)
    redirect-uri: "http://localhost:3000/auth/login/kakao"

jwt:
  access:
    secret: ENC(HRdBEGHmHvvI35Lz/vKF10ebVY66Zs4NThHIEvq0QNMBHURjZWwdpF9FgxIrREuM2I3D7QJqZuxfwt5jpVJbEfFckR7hzJWhTL2yqUYB/gOUUlXL461poK2rRM03aErRjJakPA7FTj4=)
    expiration-seconds: 3600
  refresh:
    secret: ENC(NA1bOcQ0y9gfI/dkw+6VaMnEwckOGj4jHWl2DHHCIx6yILCnvpZj59hpqg+Stp2JYqJw5MTxNUVqGX3L9NX+Hr7sExWsdaySqGeYKGNmUBodzSfqfxm5FaGjOc2K4oLE0i09xTXQIXk=)
    expiration-seconds: 1209600

server-uri: ENC(ZrgPccnQ3mEqVQTFEvGn6hzhP4xcNn6ISnp3TbBcd1J3jpZPb3hlzQ==)