spring:
  application:
    name: campus-be
  datasource:
    url: ENC(DL8go03MoJg4ysdCqMOkYx91U6D/I8l/qLTfl5kYTnA8ZUuuk3iwx0euqtwPK6Vp)
    username: ENC(qIMYoeneWcynSQCqIhxzgw==)
    password: ENC(+cc9ko9NnYMVrcpl+pPKqCyAWg1vbpaA)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: illta.campus
    password: ENC(bpaxv19TGzpHFiIiKCYIvuITX5WPYgjfmryQ0riUFvg=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

oauth:
  kakao:
    client-id: ENC(G6gZHtP5QYz7+G6herJ1QCSbdVYgjtGnx8MhBSxLDFx26Yh0YQQ+uZ6RQ7wbvS17)
    client-secret: ENC(CG823WHRi6g4ybTc/VEOfd43c/RxVnIAE+AVpYWqrE/2xnGkvtjKkVSVVOXkXBXo)
    redirect-uri: "https://138.2.121.208.nip.io/auth/login/kakao"
    admin-key: ENC(9UKWct9u8LPS0tNvuWSgqYHNN/2vvqDCYE4hRaqXsHJGCGMQY4/N1IOcbmi4IJTt)

jwt:
  access:
    secret: ENC(tUKvUNUtOcUOMRXyiFLGqmF/Wo8omGaHtXJGtqUfyiAJeNF7qmp1TpdlwYymqTbUY1kJl468BGaIahNzUGbgOvcEKhpxgkBkrkH9vNQLWRTiQbXvZtTrU+7Hl7aU0Dv0Zzx4ea9ADv4=)
    expiration-seconds: 3600
  refresh:
    secret: ENC(9CJkZOxQcIIyeYZgy6nLMcwZfh/zzdzzveWEE9BMxPe8PXiCxEqs6uICqTeYJSC76OOOvjClj0V2SSMxGjCa+HAveQ9hFWN2x/ZmgV4zWkH6mKMmHdQjNcezY3KWRzj0dtdgl0AH+js=)
    expiration-seconds: 1209600

server-uri: ENC(pitqB0FTjbgREG33LepbDH3Pobg/8eTTzP882D0V14EEt9fTr1cv+w==)