name: campus dev CD 파이프라인

on:
  workflow_run:
    workflows: ["campus CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'dev' &&
      github.event.workflow_run.head_repository.full_name == github.repository

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Docker 이미지 dev 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USERNAME}}
          key: ${{secrets.DEV_KEY}}
          script: |
            cd /home/ubuntu
            docker rm -f campus-dev || true
            docker compose pull campus-dev
            docker compose up -d --no-deps --force-recreate --pull always campus-dev
            docker image prune -f